#!/usr/bin/env python

import argparse

from pushover import pushover

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Send Pushover.net message")
    parser.add_argument('message', 
            type=str,
            help="Message to send",
            )
    parser.add_argument('--token',
            type=str,
            help="Pushover app token (overrides environment PUSHOVER_TOKEN)",
            )
    parser.add_argument('--user',
            type=str,
            help="Pushover user key (overrides ",
            )
    parser.add_argument('--title',
            type=str,
            help="Message title",
            )
    parser.add_argument('--timestamp',
            type=int,
            help="Optional UNIX timestamp",
            )
    parser.add_argument('--priority',
            type=int,
            help="Optional priority setting (0=normal, 1=high)",
            default=0,
            )
    args = parser.parse_args()

    d = {}
    for k, v in vars(args).iteritems():
        if v: d[k] = v

    pushover(**d)
